name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: api_ci_golang
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: rafaelcarvalhocaetano
        password: ${{ secrets.PASSWORD_DOCKERHUB }}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: rafaelcarvalhocaetano/ci_golang:${{ github.run_number }}
        # github-token: # optional, default is ${{ github.token }}

   