name: TESTE DE CARGA COM LOCUPES

on:
  workflow_call:

jobs:

  LOAD_TEST:
    
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - run: git clone https://github.com/leollo98/Infra_CI